n = input(' Digite algo:')
print(type(n))
print('O valor é numerico?', n.isnumeric())
print('O valor é imprimivel?', n.isprintable())
print('O valor é alfanumerico?', n.isalnum())
print('O valor é caractere?', n.isalpha())
print('O valor é ASCII?', n.isascii())
print('O valor é decimal?', n.isdecimal())
print('O valor é digito?', n.isdigit())
print('O valor é identificador?', n.isidentifier())
print('O valor é caixa baixa?', n.islower())
print('O valor é caixa alta?', n.isupper())
print('O valor é um espaço?', n.isspace())
print('O valor é um titulo?', n.istitle())

